### ISSUE TITLE
Saving booking information

### ISSUE THREAD

**Issue by ajamalen** [raybell/ticketkatjuscha#2]
Booking information has to be saved containing following information:

1. Booking number. 
That is the alphanumeric value consisting of 12 characters, which will be a time stamp of the order in the format YYYYMMDDhhmm.

2. Customer name

3. Customer email address

4. Number of the ordered tickets

5. Order amount

6. Flag if the order has been paid

7. Order date dd.MM.YYYY

8. Payment method (transfer or cash)

9. Flag if the customer has been added to email distribution list (will be marked by show organizer)

10. Community 

Through which community has advertising reached the customer? Show organizer should be able to add this information at the ticket generation time

**Comment by raybell** [comment]
xls added to handle payment/booking information
