### ISSUE TITLE
Adding the booking number to the email with bank transfer data

### ISSUE THREAD

**Issue by ajamalen** [raybell/ticketkatjuscha#4]
The booking number must be added to the bank transfer data as intended use in the email containing tickets.

For example:
Name: First name Second Name
IBAN: DEXXXXXXXXXXXXXXXXXXXX
BIC: XXXXXXXX
Betrag: 50 Euro
Verwendungszweck: Orience Mosaic Vol. 3
Verwendungszweck: 201712092352

**Comment by raybell** [comment]
booking number added to email template
